### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by levchmike** [Octonica/ClickHouseClient#35]
need support ssl certificate root. Connection yandex cloud requires ssl connection certificate

**Comment by victor-sushko** [comment]
In the version 2.1.2 added support for Transport Layer Security (TLS) connection. In order to keep a backward compatibility TLS is disabled by default. To enable TLS add the parameter `TLSMode = Require` to the connectin string.

By default the server certificate is validated with the system trusted root CA. If the server's root certificate is not installed to the system certificate store, ClickHouseClient may load it from a file.
```
TLSMode = Require; RootCertificate = ./certificates/YandexInternalRootCA.crt
```

It is also possible to pin the server's certificate by its hash. In this case the certificate with the specified hash will be considered valid despite certificate chain or host name errors.
```
TLSMode = Require; ServerCertificateHash = F647951FAB680711B40FC67B129C393B71D3576B
```

Finally, there is the property `ClickHouseConnection.RemoteCertificateValidationCallback` that allows to override validation logic. If the callback is set ClickHouseClient will use it instead of built-in methods for validating the certificate chain.

**Comment by SergeyMirvoda** [comment]
@levchmike can you try your code with latest version of library?
