### ISSUE TITLE
Exception TODO: Implement support for overflow

### ISSUE THREAD

**Issue by SergeyMirvoda** [Octonica/ClickHouseClient#9]
CH version ``20.8.3.18`` on Ubuntu 18.04

![изображение](https://user-images.githubusercontent.com/286948/93710068-115c1880-fb5d-11ea-9bc1-4753dbbf9fc4.png)

**Comment by victor-sushko** [comment]
The flag [is_overflows](https://github.com/ClickHouse/ClickHouse/blob/20.8/src/Core/BlockInfo.h#L18) is not the cause of this exception despite the message's text. This errors occured because the server had returned non-default value of [bucket_num](https://github.com/ClickHouse/ClickHouse/blob/20.8/src/Core/BlockInfo.h#L24).
It seems that the value of `bucket_num` does not indicate any changes in the structure of the block and can be ignored.
